### ISSUE TITLE
cloud-init failed on usermod to ssm-user

### ISSUE THREAD

**Issue by gotodeploy** [guan840912/cdk-gitlab-runner#147]
**Describe the bug**
As the system log below shows, a command on userData, 'usermod -aG docker ssm-user' does not work.

```
[   93.182052] cloud-init[2486]: usermod: user 'ssm-user' does not exist
```

**Expected behavior**
ssm-user should have been existed before usermod.

**Screenshots**
![Screenshot from 2020-12-09 23-13-52](https://user-images.githubusercontent.com/1491134/101640792-4b5dfc00-3a74-11eb-9909-ba2299adf73c.png)

**Additional context**

usermod command can be deleted If it's just for running docker command without sudo.

**Comment by guan840912** [comment]
Thank you for the information, ok, let's remove `usermod`
